build: resolve compile failure due to improper attribute syntax
gcc -DHAVE_CONFIG_H -I. -I../lib -I../lib -I/include      -O2 -Wall
-U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong
-funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection
-Werror=return-type -flto=auto -g  -Wcast-align -Wconversion -Wextra
-Wfloat-equal -Wimplicit-fallthrough -Wredundant-decls -Wshadow
-Wsign-compare -Wsign-conversion -Wuninitialized -Wunreachable-code
-Wunused -Wwrite-strings -c -o parser.o parser.c
In file included from c_ast.h:35,
                 from parser.y:36:
c_operator.h:243:1: warning: 'nodiscard' attribute ignored [-Wattributes]
  243 | bool c_oper_is_ambiguous( c_operator_t const *op ) {
In file included from c_operator.h:36:
c_operator.h:243:1: error: expected identifier or '(' before '_Bool'
  243 | bool c_oper_is_ambiguous( c_operator_t const *op ) {

As per https://en.cppreference.com/w/c/language/declarations ,
C2X attributes must precede specifiers like "inline".

Fixes: #22